// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/login": {
            "post": {
                "description": "\"验证用户的信息进行登入\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "login"
                ],
                "summary": "\"登入\"",
                "parameters": [
                    {
                        "description": "User",
                        "name": "User",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登入成功",
                        "schema": {
                            "$ref": "#/definitions/model.Token"
                        }
                    },
                    "400": {
                        "description": "输入格式错误"
                    },
                    "401": {
                        "description": "密码或者昵称输入错误"
                    },
                    "404": {
                        "description": "用户不存在"
                    }
                }
            }
        },
        "/match": {
            "get": {
                "description": "\"获取大赛页面的信息\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "contest"
                ],
                "summary": "\"大赛初始页面\"",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Contest"
                        }
                    },
                    "401": {
                        "description": "获取信息失败"
                    },
                    "404": {
                        "description": "验证失败"
                    }
                }
            }
        },
        "/match/search": {
            "post": {
                "description": "\"通过比赛名称对比赛进行搜索\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "contest"
                ],
                "summary": "\"搜索比赛\"",
                "parameters": [
                    {
                        "description": "temp",
                        "name": "temp",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SearchContent"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Contest"
                        }
                    },
                    "401": {
                        "description": "查询失败"
                    },
                    "404": {
                        "description": "请重试"
                    }
                }
            }
        },
        "/match/{contest_id}": {
            "get": {
                "description": "\"获取比赛的信息\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "contest"
                ],
                "summary": "\"获取信息\"",
                "parameters": [
                    {
                        "type": "string",
                        "description": "contest_id",
                        "name": "contest_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Contest"
                        }
                    },
                    "401": {
                        "description": "获取信息失败"
                    }
                }
            }
        },
        "/registe": {
            "post": {
                "description": "\"注册一个新用户\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "register"
                ],
                "summary": "\"注册\"",
                "parameters": [
                    {
                        "description": "user",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "注册成功"
                    },
                    "400": {
                        "description": "输入格式有误"
                    }
                }
            }
        },
        "/requirements": {
            "get": {
                "description": "\"获取十条招募信息并返回\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "requirements"
                ],
                "summary": "\"招募页面\"",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Requirement"
                            }
                        }
                    },
                    "401": {
                        "description": "获取失败！"
                    },
                    "404": {
                        "description": "验证失败！"
                    }
                }
            }
        },
        "/requirements/search": {
            "post": {
                "description": "\"通过招募的名称进行搜索返回多组结果\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "requirements"
                ],
                "summary": "\"招募搜索\"",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "temp",
                        "name": "temp",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SearchContent"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Requirement"
                            }
                        }
                    },
                    "401": {
                        "description": "查询失败！"
                    },
                    "404": {
                        "description": "验证失败！"
                    }
                }
            }
        },
        "/user": {
            "get": {
                "description": "\"获取用户的基本信息\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "homepage"
                ],
                "summary": "\"我的页面\"",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.UserInfo"
                        }
                    },
                    "401": {
                        "description": "没有查找到该用户的信息！"
                    },
                    "404": {
                        "description": "验证失败"
                    }
                }
            }
        },
        "/user/myrelease": {
            "get": {
                "description": "\"查看我发布的招募信息\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "homepage"
                ],
                "summary": "\"我的发布\"",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Requirement"
                            }
                        }
                    },
                    "401": {
                        "description": "获取信息失败！"
                    },
                    "404": {
                        "description": "验证失败"
                    }
                }
            }
        },
        "/user/myrelease/{require_id}": {
            "get": {
                "description": "\"通过id获取详情\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "homepage"
                ],
                "summary": "\"从我的发布中获取发布详情\"",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "require_id",
                        "name": "require_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Requirement"
                        }
                    },
                    "401": {
                        "description": "获取信息失败"
                    },
                    "404": {
                        "description": "验证失败"
                    }
                }
            }
        },
        "/user/mystore": {
            "get": {
                "description": "\"查看我的收藏\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "homepage"
                ],
                "summary": "\"我的收藏\"",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Requirement"
                            }
                        }
                    },
                    "401": {
                        "description": "没有找到信息"
                    },
                    "404": {
                        "description": "验证失败"
                    }
                }
            }
        },
        "/user/mystore/{require_id}": {
            "get": {
                "description": "\"通过id获取详情\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "homepage"
                ],
                "summary": "\"从我的发布中获取发布详情\"",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "require_id",
                        "name": "require_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Requirement"
                        }
                    },
                    "401": {
                        "description": "获取信息失败"
                    },
                    "404": {
                        "description": "验证失败"
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Contest": {
            "type": "object",
            "properties": {
                "contest_id": {
                    "type": "string"
                },
                "contest_info": {
                    "type": "string"
                },
                "contest_kind": {
                    "type": "string"
                },
                "contest_name": {
                    "type": "string"
                },
                "contest_people": {
                    "type": "string"
                },
                "contest_url": {
                    "type": "string"
                },
                "createtime": {
                    "type": "string"
                }
            }
        },
        "model.Requirement": {
            "type": "object",
            "properties": {
                "createtime": {
                    "type": "string"
                },
                "require_id": {
                    "type": "string"
                },
                "require_info": {
                    "type": "string"
                },
                "require_kind": {
                    "type": "string"
                },
                "require_number": {
                    "type": "string"
                },
                "require_title": {
                    "type": "string"
                },
                "required_need": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "model.SearchContent": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                }
            }
        },
        "model.Token": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "model.UserInfo": {
            "type": "object",
            "properties": {
                "really_name": {
                    "type": "string"
                },
                "user_college": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                },
                "user_password": {
                    "type": "string"
                },
                "user_picture": {
                    "type": "string"
                },
                "user_school": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "2021-bang",
	Description: "This is a project made by CCNU",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
