definitions:
  model.Token:
    properties:
      token:
        type: string
    type: object
  model.UserInfo:
    properties:
      really_name:
        type: string
      user_college:
        type: string
      user_id:
        type: string
      user_name:
        type: string
      user_password:
        type: string
      user_picture:
        type: string
      user_school:
        type: string
    type: object
info:
  contact: {}
  description: This is a project made by CCNU
  title: 2021-bang
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: '"验证用户的信息进行登入"'
      parameters:
      - description: User
        in: body
        name: User
        required: true
        schema:
          $ref: '#/definitions/model.UserInfo'
      responses:
        "200":
          description: 登入成功
          schema:
            $ref: '#/definitions/model.Token'
        "400":
          description: 输入格式错误
        "401":
          description: 密码或者昵称输入错误
        "404":
          description: 用户不存在
      summary: '"登入"'
      tags:
      - login
  /registe:
    post:
      consumes:
      - application/json
      description: '"注册一个新用户"'
      parameters:
      - description: user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.UserInfo'
      produces:
      - application/json
      responses:
        "200":
          description: 注册成功
        "400":
          description: 输入格式有误
      summary: '"注册"'
      tags:
      - register
swagger: "2.0"
